FROM ubuntu

ENV FLUTTER_HOME /root/flutter
ENV FLUTTER_VERSION 1.2.1-stable

RUN apt-get update \
  && apt-get install -y libglu1-mesa git curl unzip wget xz-utils lib32stdc++6 \
  && apt-get clean

RUN wget -q https://storage.googleapis.com/flutter_infra/releases/stable/linux/flutter_linux_v${FLUTTER_VERSION}.tar.xz
RUN mkdir $FLUTTER_HOME
RUN cd $FLUTTER_HOME/../ && \
	tar xf /flutter_linux_v$FLUTTER_VERSION.tar.xz

ENV PATH $PATH:$FLUTTER_HOME/bin/cache/dart-sdk/bin:$FLUTTER_HOME/bin

RUN flutter doctor
