FROM ubuntu

ENV ANDROID_SDK_HOME /opt/sdk
ENV ANDROID_SDK_VERSION 4333796

RUN apt-get update && \
	apt-get install -y openjdk-8-jdk && \
	apt-get install -y ant && \
	apt-get clean && \
	rm -rf /var/lib/apt/lists/* && \
	rm -rf /var/cache/oracle-jdk8-installer;
	
# Fix certificate issues, found as of 
# https://bugs.launchpad.net/ubuntu/+source/ca-certificates-java/+bug/983302
RUN apt-get update && \
	apt-get install -y ca-certificates-java && \
	apt-get clean && \
	update-ca-certificates -f && \
	rm -rf /var/lib/apt/lists/* && \
	rm -rf /var/cache/oracle-jdk8-installer;

RUN apt-get update && \
  apt-get install -y unzip wget && \
  apt-get clean

RUN mkdir $ANDROID_SDK_HOME

RUN cd $ANDROID_SDK_HOME && \
    wget https://dl.google.com/android/repository/sdk-tools-linux-$ANDROID_SDK_VERSION.zip
RUN cd $ANDROID_SDK_HOME && \
    unzip sdk*$ANDROID_SDK_VERSION.zip && \
    rm sdk*$ANDROID_SDK_VERSION.zip && \
    mkdir -p $ANDROID_SDK_HOME/.android && \
    touch /opt/sdk/.android/repositories.cfg

ENV JAVA_HOME /usr/lib/jvm/java-8-openjdk-amd64/
RUN export JAVA_HOME
ENV PATH $PATH:$JAVA_HOME/bin:$ANDROID_SDK_HOME/tools:$ANDROID_SDK_HOME/tools/bin

RUN java -version
RUN sdkmanager --list